name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install libpopt-dev meson
    - name: configure
      run: meson builddir
      working-directory: pico
    - name: make
      run: ninja
      working-directory: pico/builddir
