name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install libpopt-dev
    - name: autogen
      run: ./autogen.sh
      working-directory: pico
    - name: configure
      run: ./configure
      working-directory: pico
    - name: make
      run: make
      working-directory: pico
    - name: make check
      run: make check
      working-directory: pico
    - name: make distcheck
      run: make distcheck
      working-directory: pico
