name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: dependencies (Linux)
      run: sudo apt-get install libpopt-dev meson
      if: matrix.os == 'ubuntu-latest'
    - name: dependencies (MacOS)
      run: brew install meson pkg-config popt
      if: matrix.os == 'macos-latest'
    - name: configure
      run: meson builddir
    - name: make
      run: ninja
      working-directory: builddir
